service: serverless
frameworkVersion: '3'

provider:
  name: aws
  # runtime: nodejs18.x
  stackName: serverless-${opt:stage}
  environment: ${file(env.yml):${self:custom.stage}}
  apiGateway:
    restApiId: ${ssm:nextbyte-api-restApiId-${opt:stage}}
    restApiRootResourceId: ${ssm:nextbyte-api-restApiRootResourceId-${opt:stage}}
  iam:
    role: IAMServerlessRole
custom:
  stage: ${opt:stage, self:provider.stage}

package:
  individually: true
  exclude:
    - ./**
  include:
    - node_modules/**
    - package.json
    - src/http_response.js

functions:
  ping:
    runtime: python3.11
    name: ping-lambda-${opt:stage}
    package:
      include:
        - ping.js
    handler: src/ping.handler
    events:
      - http:
          path: /ping
          method: get

  courses-lambda:
    runtime: nodejs18.x
    name: courses-lambda-${opt:stage}
    package:
      include:
        - src/courses.js
        - src/coursesHandler.js
    handler: src/coursesHandler.handler
    events:
      - http:
          path: /courses
          method: get
      - http:
          path: /courses
          method: post
          cors: true

  registration-lambda:
    runtime: nodejs18.x
    name: registration-lambda-${opt:stage}
    package:
      include:
        - src/registration.js
        - src/registrationHandler.js
    handler: src/registrationHandler.handler
    events:
      - http:
          path: /registration
          method: post
          cors: true
      - http:
          path: /registration
          method: get

  students-lambda:
    runtime: nodejs18.x
    name: students-lambda-${opt:stage}
    package:
      include:
        - src/students.js
        - src/studentsHandler.js
    handler: src/studentsHandler.handler
    events:
      - http:
          path: /students
          method: post
          cors: true
      - http:
          path: /students/{studentId}
          method: get
      - http:
          path: /students
          method: get

  payments-lambda:
    runtime: nodejs18.x
    name: payments-lambda-${opt:stage}
    package:
      include:
        - src/payments.js
    handler: src/payments.handler
    events:
      - http:
          path: /pay
          method: post
          cors: true
      - http:
          path: /pay
          method: get

  materials-lambda:
    runtime: nodejs18.x
    name: materials-lambda-${opt:stage}
    package:
      include:
        - src/materials.js
        - src/materialsHandler.js
    handler: src/materialsHandler.handler
    events:
      - http:
          path: /materials
          method: get

  contact-lambda:
    runtime: nodejs18.x
    name: contact-lambda-${opt:stage}
    package:
      include:
        - src/contact.js
        - src/contactHandler.js
    handler: src/contactHandler.handler
    events:
      - http:
          path: /contact
          method: post
          cors: true

resources:
  - Resources:
      IAMServerlessRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - lambda.amazonaws.com
                Action:
                  - sts:AssumeRole
          Policies:
            - PolicyName: Policy_api-lambda-db
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - dynamodb:BatchGetItem
                      - dynamodb:BatchWriteItem
                      - dynamodb:TagResource
                      - dynamodb:UntagResource
                      - dynamodb:PutItem
                      - dynamodb:DeleteItem
                      - dynamodb:GetItem
                      - dynamodb:Scan
                      - dynamodb:Query
                      - dynamodb:UpdateItem
                    Resource:
                      - arn:aws:dynamodb:us-east-1:893303684985:table/next-byte-Students-${opt:stage}
                      - arn:aws:dynamodb:us-east-1:893303684985:table/next-byte-Courses-${opt:stage}
                      - arn:aws:dynamodb:us-east-1:893303684985:table/next-byte-Registrations-${opt:stage}
                      - arn:aws:dynamodb:us-east-1:893303684985:table/next-byte-Contact-${opt:stage}
                      - arn:aws:dynamodb:us-east-1:893303684985:table/next-byte-Students-${opt:stage}/index/EmailIndex
                  - Effect: Allow
                    Action:
                      - logs:CreateLogStream
                      - logs:CreateLogGroup
                      - logs:PutLogEvents
                    Resource: '*'
                  - Effect: Allow
                    Action:
                      - s3:GetObject
                      - s3:ListBucket
                    Resource:
                      - arn:aws:s3:::nextbyte-course-materials
                      - arn:aws:s3:::nextbyte-course-materials/*