AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create s3 bucket and policy for event registration app
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Description: Bucket on which we will deploy front end event registration app
    Properties:
      BucketName: backends3bucket-event-registration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - Date
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${MyS3Bucket}
              - !Sub arn:aws:s3:::${MyS3Bucket}/*
            Principal:
              AWS:
                - "*"
  StudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: course-registration-dynamodb-tbl
      AttributeDefinitions:
        - 
          AttributeName: !Ref HashKeyElementName
          AttributeType: !Ref HashKeyElementType
      KeySchema:
        - 
          AttributeName: !Ref HashKeyElementName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST    
Parameters:
  HashKeyElementName:
    Type: String
    Default: id
    Description: Primary Key Name
  HashKeyElementType:
    Type: String
    Default: S
    Description: Primary Key Type    
