AWSTemplateFormatVersion: 2010-09-09
Description: "Cloudformation template for back end resources, excluding lambdas"
Parameters:
  Env:
    Type: String
    AllowedValues:
      - development
      - production
    Description: The deployment environment

Conditions:
  IsDev: !Equals 
    - !Ref Env
    - development
Resources:
  ContactTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      FifoTopic: false
      Subscription: 
        - Endpoint: "info@nextbyteweb.com"
          Protocol: "email"
        - Endpoint: "dhall@nextbyteweb.com"
          Protocol: "email"
      TopicName: ContactTopic
  DynamoDBStudents:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "next-byte-Students-${Env}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: EmailIndex
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  DynamoDBCourses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "next-byte-Courses-${Env}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  DynamoDBRegistrations:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "next-byte-Registrations-${Env}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  DynamoDBTestimonials:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "next-byte-Testimonials-${Env}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  DynamoDBContact:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "next-byte-Contact-${Env}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  APIGatewayRestAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "next-byte-api-${Env}"
      EndpointConfiguration: 
        Types: 
          - REGIONAL

