AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create s3 bucket and policy for event registration app
Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Description: Bucket on which we will deploy front end event registration app
    Properties:
      BucketName: backends3bucket-event-registration
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - Date
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${MyS3Bucket}
              - !Sub arn:aws:s3:::${MyS3Bucket}/*
            Principal:
              AWS:
                - "*"
  Deployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref MyApi
      Description: My deployment
      StageName: development
    DependsOn:
      -APIGatewayMethod 
  GatewayResponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: RESOURCE_NOT_FOUND
      RestApiId: !Ref MyApi
      StatusCode: '404'
  Stack:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt 
        - MyApi
        - RootResourceId
      PathPart: stack
  Parameters:
    apiName: student-registration
      Type: String
    type:
      Type: String
  Resources:
    MyRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        EndpointConfiguration:
          Types:
            - !Ref type
        Name: !Ref MyApi