name: Deploy Back End
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        type: choice
        options:
        - development
        - production
jobs:
  Deploy_Back_End:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
          
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: next-byte-${{ github.event.inputs.environment}}
          template: ./back-end/student-tracker-template.yaml
          parameter-overrides:
            Env=${{ github.event.inputs.environment}}
  