name: Deploy Lambda Functions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        type: choice
        options:
        - development
        - production
jobs:
  Deploy_Lambdas:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: '16'
      - name: Install Dependencies
        run: npm install
        working-directory: ./back-end/Lambda
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
      - name: Deploy
        run: |
          zip -j deploy.zip ./back-end/Lambda/*
          aws lambda update-function-code --function-name=courses-lambda-${{ github.event.inputs.environment}} --zip-file=fileb://deploy.zip