name: Deploy Serverless
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        type: choice
        options:
        - development
        - production
jobs:
  Deploy_Lambdas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:  
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
      working-directory: ./serverless
    - name: serverless deploy        
      uses: serverless/github-action@master
      with:
          args: -c "cd ./serverless && serverless deploy --stage=${{ github.event.inputs.environment }}"
          entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
